name: Sync Sentences Folder Weekly

on:
  schedule:
    # 每周一00:00 UTC触发
    - cron: '0 0 * * 1'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  sync-sentences:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出当前仓库代码
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          ref: main

      # 第二步：克隆源仓库
      - name: Checkout sentences-bundle repository
        uses: actions/checkout@v3
        with:
          repository: hitokoto-osc/sentences-bundle
          ref: master
          path: sentences-bundle
        continue-on-error: false # 如果克隆源仓库失败，终止流程

      # 第三步：检查源仓库是否包含 sentences 文件夹
      - name: Verify sentences folder exists
        run: |
          if [ ! -d "sentences-bundle/sentences" ]; then
            echo "Error: sentences folder not found in sentences-bundle repository"
            exit 1
          fi

      # 第四步：复制 sentences 文件夹到当前仓库
      - name: Copy sentences folder
        run: |
          cp -r sentences-bundle/sentences/* ./sentences/

      # 第五步：检查是否有变化
      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"
        continue-on-error: false # 如果没有变化，终止流程

      # 第六步：提交并推送变化到当前仓库的 main 分支
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sentences/
          git commit -m "Sync sentences folder from hitokoto-osc/sentences-bundle"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
